mmcv-recipe v2.0.0 (#19)
* updated v2.0.0

* Add mmengine to runtime deps

Xref https://github.com/open-mmlab/mmcv/blob/v2.0.0/requirements/runtime.txt

* Rename from mmcv-full to mmcv and build using pip install . -vv

Rename package output from mmcv-full to mmcv, and build from the PyPI tar.gz file instead of the GitHub source tar.gz. Cherry-picked from https://github.com/conda-forge/staged-recipes/pull/22536. Also added LICENSE and LICENSE.md files.

* Use full url to mmcv package on PyPI

Without the {{ name }} variable.

* Partial revert to old build script

Going from PyPI back to the GitHub source.

* MNT: Re-rendered with conda-build 3.24.0, conda-smithy 3.23.1, and conda-forge-pinning 2023.05.16.03.36.14

* Add .dev_scripts/test_installation.py to source_files

Also fix some whitespaces to reduce git diff

* Trim down cuda_compiler_version if-then to just 11.2

Xref https://github.com/conda-forge/conda-forge.github.io/issues/1901.

* Add onnx, torchvision, pyturbojpeg to test.requires

* Add tifffile

* Add numpy to build requirements

See if it fixes `ImportError: cannot import name '_fastCopyAndTranspose' from 'numpy.core._multiarray_umath' (/Users/runner/miniforge3/conda-bld/mmcv-recipe_1684234509266/_build_env/venv/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so)`

* Add back pytorch(-cpu) to build dependencies

---------

Co-authored-by: Wei Ji <23487320+weiji14@users.noreply.github.com>
Co-authored-by: conda-forge-webservices[bot] <91080706+conda-forge-webservices[bot]@users.noreply.github.com>